services:
  postgres:
    image: postgres:17
    container_name: postgres-caderno-dev
    environment:
      POSTGRES_DB: caderno_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 150525
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: